---
permalink: deploy/config-limits.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: VMware vSphere용 ONTAP 툴을 구축하기 위한 구성 제한 
---
= VMware vSphere용 ONTAP 툴을 구축하기 위한 구성 제한
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 표를 참조하여 VMware vSphere용 ONTAP 툴을 구성할 수 있습니다.

|===


| * 배포 * | * 유형 * | * VVol 수 * | * 호스트 수 * | * 프로토콜 유형 * 


| 손쉬운 배포 | 소형(S) | 12K 이하 | 32 | NFS, iSCSI를 지원합니다 


| 손쉬운 배포 | 중간(M) | 24K 이하 | 64 | NFS, iSCSI를 지원합니다 


| 고가용성 | 소형(S) | 24K 이하 | 64 | NFS, iSCSI를 지원합니다 


| 고가용성 | 중간(M) | 5만 | 128 | NFS, iSCSI를 지원합니다 


| 고가용성 | 크게(L) | 100k 이하 | 256 [참고] 표에 있는 호스트 수는 여러 vCenter의 총 호스트 수를 보여 줍니다. | NFS, iSCSI를 지원합니다 
|===
노드당 호스트 시스템 크기 조정 요구 사항에 대한 자세한 내용은 을 link:../deploy/sizing-requirements.html["VMware vSphere용 ONTAP 툴을 구축하기 위한 사전 요구 사항"]참조하십시오.



== VMware vSphere용 ONTAP 툴 - SRA(Storage Replication Adapter)

다음 표에는 VMware vSphere용 ONTAP 툴을 사용하여 SRM 인스턴스당 지원되는 수가 나와 있습니다.

|===
| * vCenter 배포 크기 * | * 소형 * | * 중간 * 


| 스토리지 기반 복제를 사용하여 보호를 위해 구성된 총 가상 시스템 수입니다 | 2000 | 5000 


| 스토리지 기반 복제 보호 그룹의 총 수입니다 | 250 | 250 


| 복구 계획당 총 보호 그룹 수입니다 | 50 | 50 


| 복제된 데이터 저장소 수입니다 | 255 | 255 


| VM 수입니다 | 4000 | 7000 
|===
다음 표에는 SRM 수와 VMware vSphere 구축 크기용 ONTAP 툴의 수가 나와 있습니다.

|===


| * SRM 인스턴스 수 * | * ONTAP 도구 배포 크기 * 


| 최대 4개 | 작은 크기 


| 4 - 8 | 중간 


| 8개 이상 | 대형 
|===
자세한 내용은 을 https://docs.vmware.com/en/VMware-Live-Recovery/services/vmware-live-site-recovery/GUID-3AD7D565-8A27-450C-8493-7B53F995BB14.html["VMware Live Site Recovery의 운영상의 한계"]참조하십시오.
