---
permalink: deploy/sizing-requirements.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: VMware vSphere용 ONTAP 툴을 구축하기 전에 배포 패키지의 공간 요구 사항과 몇 가지 기본적인 호스트 시스템 요구 사항을 숙지해야 합니다. 
---
= VMware vSphere용 ONTAP 툴을 구축하기 위한 사전 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere용 ONTAP 툴을 구축하기 전에 배포 패키지의 공간 요구 사항과 몇 가지 기본적인 호스트 시스템 요구 사항을 숙지해야 합니다.

VMware vSphere용 ONTAP 툴을 VMware vCSA(vCenter Server 가상 어플라이언스)와 함께 사용할 수 있습니다. VMware vSphere용 ONTAP 툴을 ESXi 시스템이 포함된 지원되는 vSphere 클라이언트에 구축해야 합니다.

* * 노드별 설치 패키지 공간 요구 사항 *
+
** 씬 프로비저닝된 설치의 경우 10GB
** 일반 프로비저닝 설치의 경우 248GB


* * 노드당 호스트 시스템 크기 조정 요구 사항 * 배포 크기 및 노드당 권장 메모리는 아래 표와 같습니다.


|===


| * 배포 유형 * | * CPU * | * 메모리(GB) * 


| 소형(S) | 8 | 16 


| 중간(M) | 12 | 24 


| 크게(L) | 16 | 32 
|===
link:../deploy/config-limits.html["VMware vSphere용 ONTAP 툴을 구축하기 위한 구성 제한"]자세한 내용은 을 참조하십시오.



== 최소 스토리지 및 애플리케이션 요구사항

|===
| 스토리지, 호스트 및 애플리케이션 | 최소 버전 요구 사항 


| ONTAP | ONTAP 9.12.1, 9.13.1 또는 9.14.1의 최신 패치 릴리스 


| ESXi 호스트 | ESXi 7.0.3을 참조하십시오 


| vCenter Server입니다 | vCenter 7.0U3 


| VASA 공급자 | 3.0 


| OVA 응용 프로그램 | 10.1 
|===
상호 운용성 매트릭스 툴(IMT)에는 지원되는 ONTAP 버전, vCenter Server, ESXi 호스트 및 플러그인 애플리케이션에 대한 최신 정보가 포함되어 있습니다.

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["상호 운용성 매트릭스 툴"^]



== 추가 구축 고려 사항

ONTAP 도구 배포를 사용자 지정할 때 몇 가지 요구 사항을 고려해야 합니다.



=== 응용 프로그램 사용자 암호입니다

관리자 계정에 할당된 암호입니다. 보안상의 이유로 암호 길이는 8-30자로, 최소 1자, 1자, 1자리, 1개의 특수 문자를 포함하는 것이 좋습니다.



=== 어플라이언스 유지 관리 콘솔 자격 증명

""기존" 사용자 이름을 사용하여 유지 관리 콘솔에 액세스해야 합니다. 배포 중에 "성자" 사용자의 암호를 설정할 수 있습니다. vCenter Server에서 VM을 다시 시작하는 동안 사용할 수 있는 Restart guest OS 옵션을 사용하여 암호를 변경할 수 있습니다.



=== 어플라이언스 네트워크 속성입니다

유효한 DNS 호스트 이름(비정규화)과 VMware vSphere용 ONTAP 툴 및 기타 네트워크 매개 변수에 대한 정적 IP 주소를 지정하십시오. 제공된 IP 주소는 배포 중에 선택한 VLAN 네트워크에서 액세스할 수 있어야 합니다. VMware vSphere 10.1 릴리스용 ONTAP 툴에는 DHCP가 지원되지 않습니다. 이러한 모든 매개변수는 올바른 설치 및 작동에 필요합니다.
