---
permalink: protect/configure-on-srm-appliance.html 
sidebar: sidebar 
keywords:  
summary: 'SRM 어플라이언스를 배포한 후에는 SRM 어플라이언스에 SRA를 구성해야 합니다. SRA 구성이 성공하면 SRM 어플라이언스가 SRA와 통신하여 재해 복구 관리를 수행할 수 있습니다. SRM 어플라이언스와 SRA 간의 통신을 활성화하려면 VMware vSphere 자격 증명\(IP 주소 및 관리자 암호\)에 대한 ONTAP 툴을 SRM 어플라이언스에 저장해야 합니다.' 
---
= SRM 어플라이언스에 SRA를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SRM 어플라이언스를 배포한 후에는 SRM 어플라이언스에 SRA를 구성해야 합니다. SRA 구성이 성공하면 SRM 어플라이언스가 SRA와 통신하여 재해 복구 관리를 수행할 수 있습니다. SRM 어플라이언스와 SRA 간의 통신을 활성화하려면 SRM 어플라이언스에 VMware vSphere 자격 증명(IP 주소)용 ONTAP 툴을 저장해야 합니다.

* 필요한 것 *

에서 _tar.gz_파일을 다운로드해야 https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp Support 사이트"] 합니다.

* 이 작업에 대한 정보 *

SRM 어플라이언스의 SRA 구성은 SRA 자격 증명을 SRM 어플라이언스에 저장합니다.

* 단계 *

. SRM 어플라이언스 화면에서 * Storage Replication Adapter * > * New Adapter * 를 클릭합니다.
. SRM에 _.tar.gz_파일을 업로드합니다.
. putty를 사용하여 관리자 계정을 사용하여 SRM 어플라이언스에 로그인합니다.
. 다음 명령을 사용하여 루트 사용자로 전환합니다. `su root`
. 명령을 `cd /var/log/vmware/srm` 실행하여 로그 디렉토리로 이동합니다.
. 로그 위치에 명령을 입력하여 SRA에서 사용하는 Docker ID를 가져옵니다. `docker ps -l`
. 컨테이너 ID에 로그인하려면 명령을 입력합니다. `docker exec -it -u srm <container id> sh`
. 다음 명령을 사용하여 VMware vSphere IP 주소 및 암호용 ONTAP 툴을 사용하여 SRM을 구성합니다. `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <Application username> --otv-password <Application password> --vcenter-guid <VCENTER_GUID>'`
+

NOTE: Perl 스크립트가 암호의 특수 문자를 입력의 구분 기호로 읽지 않도록 하려면 암호 값을 작은따옴표로 묶어야 합니다.

. 어댑터를 다시 검색하여 SRM Storage Replication Adapters 페이지에서 세부 정보가 업데이트되었는지 확인합니다.
+
스토리지 자격 증명이 저장되었음을 확인하는 성공 메시지가 표시됩니다. SRA는 제공된 IP 주소, 포트 및 자격 증명을 사용하여 SRA 서버와 통신할 수 있습니다.


